@php($sortDirection = request('sort') === $column ? request('direction', 'asc') : null)
<span class="cm-v6-sort-heading" style="box-sizing:border-box!important;position:relative!important;width:100%!important;min-height:18px!important;display:block!important;margin:0!important;padding:0!important;color:#020617!important;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif!important;font-size:14px!important;font-weight:600!important;line-height:1.25!important;letter-spacing:0!important;text-align:center!important;text-transform:none!important;">
    <span class="cm-v6-sort-label" style="box-sizing:border-box!important;display:block!important;width:100%!important;margin:0!important;padding:0!important;color:#020617!important;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif!important;font-size:14px!important;font-weight:600!important;line-height:1.25!important;letter-spacing:0!important;text-align:center!important;text-transform:none!important;white-space:normal!important;">{{ $label }}</span>
    <span class="cm-v6-sort-arrows" style="box-sizing:border-box!important;position:absolute!important;right:0!important;top:50%!important;transform:translateY(-50%)!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:2px!important;margin:0!important;padding:0!important;color:#94a3b8!important;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif!important;font-size:14px!important;font-weight:600!important;line-height:1!important;text-align:center!important;text-transform:none!important;">
        <a href="{{ request()->url().'?'.http_build_query(array_merge(request()->except(['sort', 'direction', 'page']), ['sort' => $column, 'direction' => 'asc'])) }}"
           class="cm-v6-sort-link {{ $sortDirection === 'asc' ? 'active' : '' }}"
           style="box-sizing:border-box!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;width:8px!important;height:18px!important;margin:0!important;padding:0!important;color:{{ $sortDirection === 'asc' ? '#157144' : '#94a3b8' }}!important;background:transparent!important;border:0!important;text-decoration:none!important;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif!important;font-size:14px!important;font-weight:600!important;line-height:1!important;text-align:center!important;text-transform:none!important;"
           title="Urutkan {{ $label }} naik"
           aria-label="Urutkan {{ $label }} naik">↑</a>
        <a href="{{ request()->url().'?'.http_build_query(array_merge(request()->except(['sort', 'direction', 'page']), ['sort' => $column, 'direction' => 'desc'])) }}"
           class="cm-v6-sort-link {{ $sortDirection === 'desc' ? 'active' : '' }}"
           style="box-sizing:border-box!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;width:8px!important;height:18px!important;margin:0!important;padding:0!important;color:{{ $sortDirection === 'desc' ? '#157144' : '#94a3b8' }}!important;background:transparent!important;border:0!important;text-decoration:none!important;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif!important;font-size:14px!important;font-weight:600!important;line-height:1!important;text-align:center!important;text-transform:none!important;"
           title="Urutkan {{ $label }} turun"
           aria-label="Urutkan {{ $label }} turun">↓</a>
    </span>
</span>
