<!DOCTYPE html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Pengaturan - MA'WA CENTER</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body>
@php
    $icons=['grid'=>'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/>','database'=>'<ellipse cx="12" cy="5" rx="7" ry="3"/><path d="M5 5v12c0 1.7 3.1 3 7 3s7-1.3 7-3V5"/>','receipt'=>'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6"/>','wallet'=>'<path d="M4 6h16v14H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h13v2"/><path d="M15 11h7v5h-7a2.5 2.5 0 0 1 0-5Z"/>','card'=>'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/>','chart'=>'<path d="M4 20V10m6 10V4m6 16v-7m4 7H2"/>','settings'=>'<circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M19 5l-2 2M7 17l-2 2"/>','menu'=>'<path d="M4 6h16M4 12h16M4 18h16"/>','bell'=>'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>','logout'=>'<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4m7 14 5-5-5-5m5 5H9"/>','chevron'=>'<path d="m9 18 6-6-6-6"/>','check'=>'<path d="m5 12 4 4L19 6"/>','school'=>'<path d="m3 10 9-6 9 6-9 6-9-6Z"/><path d="M7 13v5h10v-5M3 10v7"/>','arrow'=>'<path d="M5 12h14m-6-6 6 6-6 6"/>'];
    $icon=fn($name,$class='')=>'<svg class="icon '.$class.'" viewBox="0 0 24 24" aria-hidden="true">'.$icons[$name].'</svg>';
@endphp
<div class="app-shell">
<aside class="sidebar" data-sidebar><div class="brand"><div class="brand-mark"><img src="{{ asset('images/mawa-center-mark.png') }}" alt="Logo Ma'wa Center"></div><div><strong>MA'WA <span>CENTER</span></strong><small>Manajemen Keuangan</small></div><button class="icon-button sidebar-close" data-sidebar-close>×</button></div><nav class="sidebar-nav"><a href="{{ route('dashboard') }}" class="nav-item">{!! $icon('grid') !!}<span>Dashboard</span></a><a href="{{ route('master.index') }}" class="nav-item">{!! $icon('database') !!}<span>Data Master</span></a><div class="nav-group nested-nav"><button type="button" class="nav-item nav-parent" data-nav-toggle aria-expanded="false">{!! $icon('card') !!}<span>Pembayaran</span>{!! $icon('chevron','nav-chevron') !!}</button><div class="nav-submenu"><a href="{{ route('finance.other.index',['category'=>'daftar-ulang']) }}">{!! $icon('receipt') !!}<span>Daftar Ulang</span></a><a href="{{ route('finance.spp.index') }}">{!! $icon('wallet') !!}<span>SPP</span></a><a href="{{ route('finance.other.index',['category'=>'laundry']) }}">{!! $icon('card') !!}<span>Laundry</span></a><a href="{{ route('finance.other.index') }}">{!! $icon('receipt') !!}<span>Lain-lain</span></a></div></div><a href="{{ route('finance.bills.index') }}" class="nav-item">{!! $icon('receipt') !!}<span>Tagihan</span></a><a href="{{ route('reports.index') }}" class="nav-item">{!! $icon('chart') !!}<span>Laporan</span></a><a href="{{ route('settings.index') }}" class="nav-item active">{!! $icon('settings') !!}<span>Pengaturan</span></a></nav></aside>
<div class="sidebar-overlay" data-sidebar-overlay></div><div class="main-panel"><header class="topbar"><button class="icon-button menu-toggle always-visible" data-sidebar-toggle>{!! $icon('menu') !!}</button><div class="active-year-pill"><span></span><small>Tahun Pelajaran Aktif:</small><strong>{{ $activeAcademicYear?->name ?? 'Belum diatur' }}</strong></div><div class="topbar-spacer"></div><button class="icon-button notification-button">{!! $icon('bell') !!}</button><button class="icon-button logout-button">{!! $icon('logout') !!}</button></header>
<main class="finance-page settings-page">
@if(session('success'))<div class="result-modal-backdrop show" data-alert><div class="result-modal success-result"><span class="result-icon">✓</span><strong>Sukses!</strong><p>{{ session('success') }}</p><button class="button button-primary" data-alert-close>OK</button></div></div>@endif
<section class="hero master-hero"><div><p class="eyebrow">Sistem · Pengaturan</p><h1>Pengaturan Aplikasi</h1><p>Kelola identitas sekolah dan preferensi dasar sistem keuangan.</p></div></section>
<div class="settings-layout"><form method="POST" action="{{ route('settings.update') }}" class="card settings-form">@csrf @method('PUT')
<div class="settings-form-head"><span>{!! $icon('school') !!}</span><div><strong>Identitas dan Preferensi</strong><small>Informasi ini digunakan sebagai identitas administrasi keuangan.</small></div></div>
<div class="settings-fields"><label class="wide">Nama sekolah / lembaga<input name="school_name" value="{{ old('school_name',$settings['school_name']) }}" required></label><label>Nomor telepon<input name="school_phone" value="{{ old('school_phone',$settings['school_phone']) }}"></label><label>Email<input type="email" name="school_email" value="{{ old('school_email',$settings['school_email']) }}"></label><label class="wide">Alamat<textarea name="school_address" rows="3">{{ old('school_address',$settings['school_address']) }}</textarea></label><label>Penanggung jawab keuangan<input name="finance_officer" value="{{ old('finance_officer',$settings['finance_officer']) }}"></label><label>Metode pembayaran utama<select name="default_payment_method"><option @selected($settings['default_payment_method']==='Cash')>Cash</option><option @selected($settings['default_payment_method']==='Transfer')>Transfer</option></select></label><label class="wide">Pesan footer struk<textarea name="receipt_footer" rows="2">{{ old('receipt_footer',$settings['receipt_footer']) }}</textarea></label></div>
<div class="settings-save"><span>Pastikan informasi sudah benar sebelum menyimpan.</span><button class="button button-primary">Simpan Pengaturan</button></div></form>
<aside class="settings-side"><section class="card setup-card"><div class="settings-form-head"><span>{!! $icon('check') !!}</span><div><strong>Kelengkapan Sistem</strong><small>Ringkasan data aktif saat ini.</small></div></div>@foreach(['units'=>['Unit Pendidikan','education-units'],'classes'=>['Kelas','classes'],'students'=>['Siswa','students'],'fee_types'=>['Jenis Pembayaran','fee-types'],'spp_settings'=>['Set SPP','spp-settings']] as $key=>$item)<a href="{{ route('master.index',['tab'=>$item[1]]) }}"><span>{{ $item[0] }}</span><strong>{{ $setup[$key] }}</strong>{!! $icon('arrow') !!}</a>@endforeach</section><section class="settings-note"><strong>Catatan</strong><p>Pengaturan nominal SPP, jenis pembayaran, kelas, dan siswa tetap dikelola melalui menu Data Master.</p></section></aside></div>
</main></div></div>
</body></html>
